# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d882c22cb25ec605ead5a0f56beed484aed7776dfc0bb3ad06f36dae23ff3ee956c4c08f155aa8afb68a8ddb0fb8618f06e51b60beca4da9c7a3651bc75e77da

test:
  secret_key_base: f20a30488e4e24811cd870c5c9cab364078c337ab9305bb93ad4e0bdef5b8bd3082ac923d79d8488af62eb6e7e7e40c233796eefc724d35a1fdc85d97a501b79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
